TEXT = {
    'lblLanguage': ['Language', 'زبان'],
    'lblSettingsHeader': ['Settings', 'تنظیمات'],
    'btnUiSettings': [' User Interface',' رابط کاربری'],
    'btnUmSettings': [' User Management',' مدیریت کاربران'],
    'btnHwSettings': [' Hardware   ', ' سخت افزار'],
    'lblUserNumber': ['Enter user phone number', 'شماره تلفن کاربر را وارد کنید'],
    'txtNumber': ['Number', 'شماره'],
    'btnStartSession': [' Start Session', ' شروع جلسه'],
    'btnStartUserSession': [' Start Session', 'شروع جلسه '],
    'lblHeaderTutorials': ['Tutorials', 'آموزش ها'],
    'lblVideos': ['Videos', 'فیلم ها'],
    'lblTitle': ['Title', 'عنوان'],
    'lblHeaderFsessions': ['Future Sessions', 'جلسه های آینده'],
    'tbFsessions0': ['Phone Number', 'شماره تلفن'],
    'tbFsessions1': ['Name', 'نام'],
    'tbFsessions2': ['Session Number', 'شماره جلسه'],
    'tbFsessions3': ['Last Session', 'آخرین جلسه'],
    'lblHeaderUm': ['User Management', 'مدیریت کاربران'],
    'usersTable0': ['Phone Number', 'شماره تلفن'],
    'usersTable1': ['Name', 'نام'],
    'usersTable2': ['Sessions', 'تعداد جلسات'],
    'usersTable3': ['Action', 'عملیات'],
    'btnSort': ['Sort By Session', 'مرتب سازی جلسات'],
    'txtSearch': ['Search...', 'جستوجو...'],
    'lblName': ['Name', 'نام'],
    'lblPhoneNumber': ['Phone Number', 'شماره تلفن'],
    'lblNextSession': ['Next Session', 'جلسه بعدی'],
    'lblHeaderUserInfo': ['User Information', 'اطلاعات کاربر'],
    'lblUserInfo': ['User Information', 'اطلاعات کاربر'],
    'btnNextSession': [' Next Session', 'جلسه بعد '],
    'btnSaveHw': ['Save', 'ذخیره'],
    'btnSaveInfo': [' Save', 'ذخیره '],
    'btnDeleteUser': ['Delete', 'حذف'],
    'userInfoTable0': ['Date', 'تاریخ'],
    'userInfoTable1': ['Face', 'صورت'],
    'userInfoTable2': ['Armpit', 'زیربغل'],
    'userInfoTable3': ['Arm', 'بازو'],
    'userInfoTable4': ['Body', 'بدن'],
    'userInfoTable5': ['Bikini', 'بیکینی'],
    'userInfoTable6': ['Leg', 'پا'],
    'lblMFace': ['Face', 'صورت'],
    'lblMArmpit': ['Armpit', 'زیربغل'],
    'lblMArm': ['Arm', 'بازو'],
    'lblMBody': ['Body', 'بدن'],
    'lblMBikini': ['Bikini', 'بیکینی'],
    'lblMLeg': ['Leg', 'پا'],
    'lblFFace': ['Face', 'صورت'],
    'lblFArmpit': ['Armpit', 'زیربغل'],
    'lblFArm': ['Arm', 'بازو'],
    'lblFBody': ['Body', 'بدن'],
    'lblFBikini': ['Bikini', 'بیکینی'],    
    'lblFLeg': ['Leg', 'پا'],        
    'userInfoTable7': ['Total', 'جمع کل'],
    'notSet': ['Not Set', 'تنظیم نشده'],
    'today': ['Today', 'امروز'],
    '1dayPassed': ['One Day Passed', 'یک روز گذشت'],
    '1dayleft': ['One Day left', 'یک روز باقی مانده'],
    'nDayPassed': ['Days passed', 'روز گذشت'],
    'nDayLeft': ['Days left', 'روز باقی مانده'],
    'passedDate': ['A past date cannot be set.', 'تاریخ گذشته قابل تنظیم نیست.'],
    'invalidDateF':['Invalid date format.', 'قالب تاریخ نامعتبر است.'],
    'emptyNumber': ['Please fill in the number.', 'لطفا شماره را وارد کنید.'],
    'userBeenDeleted': ['User has been deleted!', 'کاربر حذف شده است!'],
    'alreadyExists': ['A user with this phone number already exists!', 'کاربری با این شماره تلفن از قبل وجود دارد!'],
    'userUpdated': ["User's info Updated.", 'اطلاعات کاربر به روز شد.'],
    'sssionNotOver': ['The previous session is not over yet.', 'جلسه قبلی هنوز تموم نشده است.'],
    'alreadyExistsSub': ['User already exists!', 'کاربر از قبل وجود دارد.'],
    'lblDate': ['Date', 'تاریخ'],
    'lblDaysNS': ['Days', 'روز'],
    'lblDaysAfter': ['Next Session After', 'جلسه بعدی، بعد از'],
    'btnCancelNS': ['Cancel', 'لغو'],
    'btnLaterNS': ['Later', 'بعدا'],
    'btnOkNS': ['OK', 'ثبت'],
    'lblHeaderNextSession': ['Next Session', 'جلسه بعدی'],
    'lblHeaderNewUser': ['New User', 'کاربر جدید'],
    'lblEnterUserInfo': ['Enter the user information', 'مشخصات کاربر را وارد کنید'],
    'txtNumberSubmit': ['Number', 'شماره'],
    'txtNameSubmit': ['Name', 'نام'],
    'btnSubmit': ['Submit', 'ثبت'],
    'btnEndSession': [' End Session', ' پایان جلسه'],
    'btnFemale': ['Female', ' زن '],
    'btnMale': [' Male    ',' مرد '],
    'lblEnergy': ['Energy', 'انرژی'],
    'lblFrequency': ['Frequency', 'فرکانس'],
    'lblPulseWidth': ['Pulse Width', 'پهنای پالس'],
    'lblCounter': ['Counter', 'شمارنده'],
    'lblJoule': ['Joule', 'ژول'],
    'lblmSec': ['mSec', 'میلی ثانیه'],
    'lblHz': ['Hz', 'هرتز'],
    'lblEnergyCalib': ['Energy   →', '→   انرژی'],
    'lblJouleCalib': ['Joule', 'ژول'],
    'lblPulseWidthCalib': ['Pulse Width   →', '→   پهنای پالس'],
    'lblmSecCalib': ['mSec', 'میلی ثانیه'],
    'lblFrequencyCalib': ['Frequency   →', '→   فرکانس'],
    'lblHzCalib': ['Hz', 'هرتز'],
    'face': ['Face', 'صورت'],
    'armpit': ['Armpit', 'زیربغل'],
    'arm': ['Arm', 'بازو'],
    'body': ['Body', 'بدن'],
    'bikini': ['Bikini', 'بیکینی'],
    'leg': ['Leg', 'پا'],
    'btnReady': ['Ready', 'آماده'],
    'btnReadyCalib': ['Ready', 'آماده'],
    'btnStandby': ['Standby', 'غیر فعال'],
    'btnStandByCalib': ['Standby', 'غیر فعال'],
    'lblSpotSizeCalib': ['Spot Size Area', 'مساحت نقطه تابش'],
    'lblSpotSize': ['Spot Size Area', 'مساحت نقطه تابش'],
    'lblReadValue': ['Read Value', 'مقدار خوانده شده'],
    'lblCurrentCoeff': ['Current Coeff', 'ضریب فعلی'],
    'btnApplyCoeff': ['Apply Coefficient', 'اعمال ضریب'],
    'total': ['Total','جمع کل'], 
    'firstTime': ['First Time', 'اولین جلسه'],
    'lblSerialNumber': ['Serial Number', 'شماره سریال'],
    'lblTotalShotCounter': ['Total Shot Counter', 'مجموع شات ها'],
    'lblLaserDiodeEnergy': ['Laser Diode Energy', 'سطح انرژی لیزر'],
    'lblLaserBarType': ['Laser Bar Type', 'نوع لیزر بار'],
    'lblLaserWavelength': ['Laser Wavelength', 'طول موج لیزر'],
    'lblDriverVersion': ['Driver Version', 'ورژن درایور'],
    'lblMainControlVersion': ['Main Control Version', 'ورژن برد کنترل'],
    'lblFirmwareVersion': ['Firmware Version', 'ورژن فریموور'],
    'lblProductionDate': ['Production Date', 'تاریخ تولید'],
    'lblOsSpecification': ['OS Specification', 'سیستم عامل'],
    'lblMonitor': ['Monitor', 'نمایشگر'],
    'lblRpiVersion': ['RPi Version', 'ورژن رزبری پای'],
    'lblGuiVersion':['GUI Version', 'ورژن رابط کاربری'],
    'btnEnterHw': ['Enter', 'ورود'],
    'txtHwPass': ['Password', 'رمز عبور'],
    'saveHw': ['Updated.', 'بروزرسانی شد.'],
    'systemTimeStatusError': ['Could not set system time.', 'زمان سیستم تنظیم نشد.'],
    'systemTimeStatus': ['Time updated successfully.', 'زمان با موفقیت تنظیم شد.'],
    'btnResetCounter': ['Reset Counter', 'ریست شمارنده'],
    'btnResetCounter2': ['Reset', 'ریست'],
    'lblProducion': ['Production', 'تولید'],
    'lblLaser': ['Laser', 'لیزر'],
    'lblDriver': ['Driver', 'درایور'],
    'lblEmbedded': ['Embedded System', 'سیستم تعبیه شده'],
    'lblSkinGrade': ['Skin Grade', 'گرید پوستی'],
    'lblCooling': ['Cooling', 'سرمایش'],
    'btnHwinfo': ['System Info', 'اطلاعات سیستم'],
    'btnSystemLock': ['Lock && Time', 'قفل و زمان'],
    'lblDefineLock': ['Define a Lock', 'تعریف یک قفل'],
    'lblSysClock': ['System Clock', 'ساعت سیستم'],
    'lblSysDate': ['System Date', 'تاریخ سیستم'],
    'lblEditClock': ['Edit Clock', 'تنظیم ساعت'],
    'lblEditDate': ['Edit Date', 'تنظیم تاریخ'],
    'tableLock0': ['Date', 'تاریخ'],
    'tableLock1': ['Status' ,'وضعیت'],
    'tableLock2': ['Paid', 'پرداخت شده'],
    'anyLockBefor': ['The lock date must be earlier than the last one.', 'تاریخ قفل باید از تاریخ اخرین قفل جلوتر باشد.'],
    'maxLock': ['A maximum of 3 locks can be defined.', 'حداکثر 3 قفل می تواند تعریف شود.'],
    'yes': ['Yes', 'بله'],
    'no': ['No', 'خیر'],
    'lblCurrentUser': ['Name', 'نام'],
    'lblCurrentSnumber': ['Session', 'جلسه'],
    'tempError': ['Temperature Sensor Error', 'خطای سنسور دما'],
    'waterflowError': ['Water Flow Sensor Error', 'خطای سنسور جریان آب'],
    'waterLevelError': ['Water Level Sensor Error', 'خطای سنسور سطح آب'],
    'interLockError': ['Inter Lock Switch Error', 'خطای سوئیچ قفل داخلی'],
    'overHeatError': ['Over Heat Error', 'خطای گرمای بیش از حد'],
    'physicalDamage': ['Physical Damage', 'آسیب فیزیکی'],
    'lblOwnerInfo': ['Owner Information', 'اطلاعات مالک'],
    'btnShowSplash': ['Splash Page', 'صفحه اسپلش'],
    'btnUpdateFirmware': ['Update Firmware', 'بروزرسانی فریموور '],
    'lblSlideTransition': ['Slide Transition', 'گذر اسلاید'],
    'lblTouchSound': ['Touch Sound', 'صدای تاچ'],
    'lblTheme': ['Themes', 'تم ها'],
    'daysLater': ['Days Later', 'روز بعد'],
    'tomorrow': ['Tomorrow', 'فردا'],
    'lblShowSession': ['Sessions After', 'جلسه های بعد از'],
    'lblDaysFS': ['Days', 'روز'],
    'btnRefreshFS': ['Refresh', 'تازه سازی'],
    'lblTotalUsers': ['Total Users', 'تعداد کل'],
    'btnPower': [' Power Off', '     خاموش'],
    'btnRestart': [' Restart     ', 'ری استارت'],
    'lblSelectedUsers': ['Selected Users', 'انتخاب شده'],
    'btnDelSelectedUsers': ['Remove', 'حذف کردن'],
    'btnDeselectAll': ['Deselect All', 'لغو انتخاب'],
    'btnSelectAll': ['Select All', 'انتخاب همه'],
    'saveConfigError': ['Error saving settings.', 'خطای ذخیره تنظیمات.'],
    'btnSystemLogs': ['System Logs', 'لاگ سیستم'],
    'btnFindNext': ['Find Next', 'بعدی'],
    'btnFindBefor': ['Find Previous', 'قبلی'],
    'txtSearchLogs': ['Search...', 'جستوجو...'],
    'btnDeleteLogs': ['Delete Logs', 'حذف لاگ ها'],
    'txtSearchMusic': ['Search...', 'جستوجو...'],
    'lblMusicHeader': ['Musics', 'آهنگ ها'],
    'btnLoadMusic': ['Load', 'بارگذاری'],
    'txtResetCounterPass': ['Password', 'رمز'],
    'btnResetCounterPass': ['Reset', 'ریست'],
    'btnHwTesst': ['Hardware Test', 'تست سیستم'],
    'lblcpRightPass': ['Passwoed', 'رمز عبور'],
    'lblYourId': ['ID', 'شناسه'],
    'lblLicPass': ['Passwoed', 'رمز عبور'],
    'btnUUIDEnter': ['Enter', 'ورود'],
    'lblLicID': ['License ID', 'شماره مجوز'],
    'btnEnter': ['Enter', 'ورود'],
    'wrongPass': ['Password is not correct.', 'رمز عبور صحیح نمی باشد.'],
    'lblLicMsg': [
            'Your laser machine has been locked for maintenance purpose.\nFor more information contact to Behdad Beauty company.\nTelephone +98 922 491 6671',
            'دستگاه لیزر شما به منظور انجام سرویس های دوره ای غیرفعال شده است.\nبرای اطلاعات بیشتر با شرکت بهداد بیوتی تماس بگیرید.\nتلفن  6671 491 922 98+'
            ],
    'btnResetMsgYes': ['Yes', 'بله'],
    'btnResetMsgNo': ['No', 'خیر'],
    'lblResetMsg': ['Are you sure?', 'مطمئن هستید؟'],
    'btnCalibration': ['Calibration', 'کالیبراسیون'],
    'btnHandpiece': [' Handpiece TEC', ' خنک کننده هندپیس'],
    'btnRadiator': [' Radiator TEC', ' خنک کننده رادیاتور'],
    'btnLaserPower': [' Laser Power', ' تغذیه لیزر'],
    'btnAirCooling': [' Air Cooling', ' خنک کننده هوا'],
    'btnReserved': [' Reserved', ' رزرو شده'],
    'btnPowerOnOffRelay': [' Power On/Off', ' تغذیه خاموش/روشن'],
    'btnDriverCurrentStart': ['Driver Current', 'جریان درایور'],
    'btnDacVoltageTest': [' DAC Voltage', ' ولتاژ درایور'],
    'btnSetDac': ['Set', 'تنظیم'],
    'lblDriverVoltage': ['Voltage   →', '→   ولتاژ'],
    'btnInterLockTest': ['Inter Lock', 'قفل سخت افزاری'],
    'btnWTSTest': ['Water Temp Sensor', 'سنسور دمای آب'],
    'btnHandpieceTempTest': ['Handpiece Temp', 'سنسور دمای هندپیس'],
    'btnWaterLevelTest': [' Water Level', 'سطح آب'],
    'btnFlowMeterTest': [' Flow Meter', ' گردش آب'],
    'btnAirTempSensorTest': [' Air Temp Sensor', 'سنسور دمای هوا'],
    'relaysBox': [' Relays', ' رله ها'],
    'driverFunctionalityBox': [' Driver Functionality', ' عملکر درایور'],
    'sensorsBox': [' Sensors',' حسگر ها'],
    'btnInterLockPass': ['Unlocked', 'باز'],
    'btnInterLockFail': ['Locked', 'قفل'],
    'btnWaterLevelPass': ['OK', 'قبول'],
    'btnWaterLevelFail': ['Not OK', 'مردور'],
    'btnPassHP': ['Pass', 'قبول'],
    'btnFailHP': ['Fail', 'مردود'],
    'btnPassRad': ['Pass', 'قبول'],
    'btnFailRad': ['Fail', 'مردود'], 
    'btnPassLP': ['Pass', 'قبول'], 
    'btnFailLP': ['Fail', 'مردود'],
    'btnPassAC': ['Pass', 'قبول'],
    'btnFailAC': ['Fail', 'مردود'],
    'btnPassRes': ['Pass', 'قبول'],
    'btnFailRes': ['Fail', 'مردود'], 
    'btnPassPower': ['Pass', 'قبول'], 
    'btnFailPower': ['Fail', 'مردود'],
    'SensorError': ['Sensor Error', 'خطای سنسور'],
    'saveCoeffError': ['Error saving coefficient.', 'خطای ذخیره ضریب'],
    'CoeffError': ['Invalid input', 'ورودی نامعتبر'],
    'saved': ['Saved.', 'ذخیره شد.'],
    'Coeff': ['Coeff  →  ', 'ضریب  ←  '],
    'lblTutorialMsg': ["Please put your videos in tutorials folder.", "لطفا ویدئوهای خود را در پوشه tutorials قرار دهید."]
}